<script type="text/javascript" >
var imagens  = new Array( 'controleChamados.png', 'listaCasamento.png', 'quadroCredores.png','quadroJudicial.png','rnc.png','simulador.png');
var num_img  = 6;
var img_atual = 0;
function ChangeImg(){
    if (img_atual < (num_img - 1) ){
        img_atual = img_atual + 1;
   }else{
        img_atual = 0;
   }
    document["img_apoio"].src    = "imgProjetos/" + imagens[img_atual];
   var x = setTimeout ("ChangeImg()", 4000);
}
</script>
<body onload="ChangeImg()"  >
<div  style="width: 980px; position: absolute; top: 173px; height: 799px; left: 0px;" class="s3" data-state="" id="PAGES_CONTAINER" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER">
   <div data-gallery-id="mainPage_SlideShowGallery_1" data-height-diff="0" data-width-diff="0" class="s20" data-state="hidePlayButton autoplayOn notMobile desktopView touchRollOut " id="mainPage_SlideShowGallery_1" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$mainPage_SlideShowGallery_1" >
                       
                       <!-- Projetos -->
      <div data-lightbox="listaProjetos"  >
          <a href="imgProjetos/controleChamados.png" data-title="Controle de Chamados" data-lightbox="listaProjetos"><img class="fotos" name="img_apoio" alt="" src="imgProjetos/controleChamados.png" height="345">
          </a>  
      </div>
      <div data-lightbox="listaProjetos"  >
          <a href="imgProjetos/listaCasamento.png" data-title="Lista de Casamento" data-lightbox="listaProjetos"><img alt="" src="imgProjetos/listaCasamento.png" height="315">
          </a>  
      </div>  
      <div data-lightbox="listaProjetos"  >
          <a href="imgProjetos/quadroJudicial.png" data-title="Quadro de Credores" data-lightbox="listaProjetos"><img alt="" src="imgProjetos/quadroJudicial.png" height="315">
          </a>  
      </div>   
      <div data-lightbox="listaProjetos"  >
          <a href="imgProjetos/quadroCredores.png" data-title="Quadro de Credores(Controle)" data-lightbox="listaProjetos"><img alt="" src="imgProjetos/quadroControle.png" height="315">
          </a>  
      </div>   
      <div data-lightbox="listaProjetos"  >
          <a href="imgProjetos/rnc.png" data-title="Registro de Não Conformidades" data-lightbox="listaProjetos"><img alt="" src="imgProjetos/rnc.png" height="315">
          </a>  
      </div> 
      <div data-lightbox="listaProjetos"  >
          <a href="imgProjetos/simulador.png" data-title="Simulador de Combate" data-lightbox="listaProjetos"><img alt="" src="imgProjetos/simulador.png" height="315">
          </a>  
      </div>   
                       <!-- fim exibição -->      
   </div>
   <div class="s1" id="mainPage_WRichText_2" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$mainPage_WRichText_2">
      <h5 class="font_5" style="line-height: 1.2em; text-align: justify;"><span><span class="color_23">Sobre</span></span></h5>
      <p class="font_8" style="text-align: justify;">&nbsp;</p>
      <p class="font_8" style="text-align: justify;">&nbsp;</p>
      <p class="font_8" style="text-align: justify;">Desenvolvemos sistemas que atendam as necessidade de sua empresa.</p>
      <p class="font_8" style="text-align: justify;">Os sistemas precisam se adequarem a empresa e não a empresa ao sistema para isso nos disponibilizamos a atendê-lo...</p>
    </div>
    <div style="" class="s2" id="mainPage_FiveGridLine_4" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$mainPage_FiveGridLine_4"></div>
    <div class="s2" id="mainPage_FiveGridLine_3" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$mainPage_FiveGridLine_3"></div>
    <div class="s6" id="FvGrdLn3" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$FvGrdLn3"></div>
    <div class="s2" id="FvGrdLna" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$FvGrdLna">
       <div id="FvGrdLnaline" class="s2line" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$FvGrdLna.0"></div>
    </div>
    <div class="s1" id="WRchTxte" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$WRchTxte">
       <h5 class="font_5" style="line-height: 1.2em; text-align: justify;">
          <span><span class="color_28">Projetos</span></span>
       </h5>
       <p class="font_8" style="text-align: justify;">&nbsp;</p>
       <p class="font_8" style="text-align: justify;">&nbsp;</p>
       <p class="font_8" style="text-align: justify;">Apresentamos nosso portfólio a fim de darmos uma ideia de como podemos ajudá-lo na gestão de sua empresa.&nbsp;</p>
    </div>
    <div class="s1" id="WRchTxtl" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$WRchTxtl">
       <h5 class="font_5" style="line-height:1.2em"><span><span class="color_19">Pensamento</span></span></h5>
       <p class="font_7" style="line-height:1.3em"><span><span class="color_19">​</span></span></p>
       <p class="font_8">"Com organização e tempo, acha-se o segredo de fazer tudo e bem feito."</p>
       <p class="font_8"><span class="color_18"><a href="https://pt.wikipedia.org/wiki/Pit%C3%A1goras" target="_blank" ><span style="font-weight:bold;">&nbsp;Pitágoras</span></a></span></p>
     </div>
     <div class="s6" id="FvGrdLnc" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$FvGrdLnc"></div>
     <div class="s1" id="WRchTxtd" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$WRchTxtd">
         <h3 class="font_3" style="line-height:1.1em"><span class="color_19">SOLUÇÕES EM</span></h3>
         <h3 class="font_3" style="line-height:1.1em"><span class="color_19">SISTEMAS</span></h3>
         <p class="font_7">&nbsp;</p>
         <p class="font_8" style="line-height:1.3em"><span class="color_19">​</span></p>
         <p class="font_7"><span class="color_19">Personalize o sistema de sua empresa.</span></p>
         <p class="font_7"><span class="color_19">A EMQDesenv ajuda nos negócios de sua empresa.</span></p>
         <p class="font_7"><span class="color_19">Sistema todo desenvolvido em PHP.</span></p>
      </div>
      <div id="StBttn1" data-align="center" data-disabled="false" data-margin="0" data-should-use-flex="true" class="s21" data-state="desktop shouldUseFlex center" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$StBttn1" data-prev-text="Saiba mais" data-prev-min-width="65" data-prev-width="116">
          <a href="index.php?pagina=Projetos" target="_self" id="StBttn1link" class="g-transparent-a s21link" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$StBttn1.0"><span id="StBttn1label" class="s21label" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$StBttn1.0.0" style="">Saiba mais</span></a>
      </div>
      <div id="StBttn3" data-align="center" data-disabled="false" data-margin="0" data-should-use-flex="true" class="s22" data-state="desktop shouldUseFlex center" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$StBttn3" data-prev-text="Saiba mais" data-prev-min-width="65" data-prev-width="108">
          <a href="index.php?pagina=Sobre" target="_self" id="StBttn3link" class="g-transparent-a s22link" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$StBttn3.0"><span id="StBttn3label" class="s22label" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$mainPage_DESKTOP.1.$StBttn3.0.0" style="">Saiba mais</span></a>
      </div>
</div> 
</body>