<div id="SITE_CONTAINER">
   <div class="s3" data-state="" id="PAGES_CONTAINER" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER">
      <div class="s1" id="WRchTxt1-452" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$WRchTxt1-452">
          <h5 class="font_5" style="line-height:1.2em"><span><span class="color_19">Controle de Chamados</span></span></h5>
          <p class="font_8">&nbsp;</p>
          <p class="font_8">&nbsp;</p>
          <p class="font_8" style="text-align: justify;">Desenvolvido para um 
controle eficiente dos incidentes ocorridos em sua empresa, podendo 
assim projetar soluções que previnam ocorrências futuras.&nbsp;</p>
          <br>
          <div><iframe width="222" height="160" src="https://www.youtube.com/embed/6QX2xXW6v3I?feature=oembed" frameborder="0" allowfullscreen></iframe></div>
      </div>
      <div class="s2" id="FvGrdLn2-zxn" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$FvGrdLn2-zxn"></div>
         <div class="s9" id="Cntnr0" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$Cntnr0">
             <div id="Cntnr0bg" class="s9bg" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$Cntnr0.0"></div>
             <div class="s1" id="WRchTxtk" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$Cntnr0.1.$WRchTxtk">
                <p class="font_7">&nbsp;</p>
                <h3 class="font_3" style="line-height:1.1em"><span style="font-size:42px;"><span class="color_11">ESTES SISTEMAS FORAM DESENVOLVIDOS PARA SUA EMPRESA</span></span><span style="font-size:48px"><span><span class="color_11"> </span></span></span></h3>
                <p class="font_8" style="line-height:1.3em"><span><span class="color_11">​</span></span></p>
                <p class="font_8" style="line-height:1.3em"><span><span class="color_11">​</span></span></p>
                <p class="font_8"><span class="color_11">Analisamos as atividades de sua empresa e adaptamos o sistema as necessidades para sua comodidade e sucesso.</span></p>
             </div>
         </div>
         <div class="s1" id="WRchTxtg" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$WRchTxtg">
            <h2 style="line-height: 1.1em;" class="font_2"><span style="line-height: 1.1em;"><span class="color_19">Projetos</span></span></h2>
         </div>
         <div class="s2" id="FvGrdLni" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$FvGrdLni"></div>
         <div style="" class="s2" id="FvGrdLnj" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$FvGrdLnj"></div>
         <div class="s2" id="FvGrdLnk" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$FvGrdLnk"></div>
         <div class="s2" id="FvGrdLnd" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$FvGrdLnd"></div>
         <div class="s1" id="WRchTxt0-84w" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$WRchTxt0-84w">
             <h5 class="font_5" style="line-height:1.2em"><span><span class="color_19">Registro de Não&nbsp; Conformidades</span></span></h5>
             <p class="font_8">&nbsp;</p>
             <p class="font_8">&nbsp;</p>
             <p class="font_8" style="text-align: justify;">Este programa tem como objetivo a distribuição de responsabilidades,<br>
garantindo maior trabalho em equipe, agilidade e eficácia nas tratativas das não conformidades:</p>
             <br>
             <div><iframe width="222" height="160" src="https://www.youtube.com/embed/D_6ZfJc-JcI?feature=oembed" frameborder="0" allowfullscreen></iframe></div>
             <p class="font_8"><span class="wixGuard">​</span></p>
         </div>
         <div class="s1" id="comp-ivij4wdk" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivij4wdk">
            <h5 class="font_5" style="line-height:1.2em"><span><span class="color_19">Quadro de Credores</span></span></h5>
            <p class="font_8">&nbsp;</p>
            <p class="font_8">&nbsp;</p>
            <p class="font_8" style="text-align: justify;">Em uma liquidação é necessário a publicação do quadro de credores.</p>
            <p class="font_8" style="text-align: justify;">Este programa foi desenvolvido para ajudá-lo neste serviço.</p>
            <p class="font_8"><span class="wixGuard">​</span></p>
         </div>
         <div data-exact-height="170" data-content-padding-horizontal="2" data-content-padding-vertical="2" title="" class="s10" id="comp-ivik0w28" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivik0w28">
            <img id="comp-ivik0w28imgimage" alt="" src="img/5a8c4b_cf03130af32640bb9dc5e6d377b8a8d8~mv2.png"  data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivik0w28.0.0.$image">
         </div>
         <div id="comp-ivilyhfo" data-align="center" data-disabled="false" data-margin="0" data-should-use-flex="true" class="s11" data-state="desktop shouldUseFlex center" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivilyhfo" data-prev-text="Ver" data-prev-min-width="19" data-prev-width="55">
            <!--<a href="videos/chamados.htm" target="_self" data-no-physical-url="http://emquintino.wixsite.com/emqdesenv/popup-dyiyr" id="comp-ivilyhfolink" class="g-transparent-a s11link" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivilyhfo.0"><span id="comp-ivilyhfolabel" class="s11label" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivilyhfo.0.0" style="">Ver</span>
            </a>-->
         </div>
         <div id="comp-ivjmnb4r" data-align="center" data-disabled="false" data-margin="0" data-should-use-flex="true" class="s11" data-state="desktop shouldUseFlex center" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivjmnb4r" data-prev-text="Ver" data-prev-min-width="19" data-prev-width="55">
             <!--<a href="videos/rnc.htm" target="_self" data-no-physical-url="http://emquintino.wixsite.com/emqdesenv/popup-dyiyt" id="comp-ivjmnb4rlink" class="g-transparent-a s11link" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivjmnb4r.0"><span id="comp-ivjmnb4rlabel" class="s11label" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivjmnb4r.0.0" style="">Ver</span>
             </a>-->
         </div>
         <div id="comp-ivjn5s10" data-align="center" data-disabled="false" data-margin="0" data-should-use-flex="true" class="s11" data-state="desktop shouldUseFlex center" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivjn5s10" data-prev-text="Ver" data-prev-min-width="19" data-prev-width="55">
             <a href="javascript:void()" target="_self" data-no-physical-url="http://emquintino.wixsite.com/emqdesenv/popup-dyiyt" id="comp-ivjn5s10link" class="g-transparent-a s11link" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivjn5s10.0" onclick="alert('Acesso restrito')"><span id="comp-ivjn5s10label" class="s11label"  title="Acesso restrito" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$ctzx_DESKTOP.1.$comp-ivjn5s10.0.0" style="">Ver</span>
             </a>
         </div>
    </div>
</div>