<div class="s3" data-state="" id="PAGES_CONTAINER" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER">
    <div data-exact-height="412" data-content-padding-horizontal="2" data-content-padding-vertical="2" title="" class="s10" id="WPht1" >
       <div id="WPht1link" class="s10link" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WPht1.0">
          <img id="WPht1imgimage" alt="" src="img/84770f_e5c72873af0c989891d567202de3967d.jpg" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WPht1.0.0.$image">
       </div>
    </div>
    <div class="s1" id="WRchTxt13" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WRchTxt13">
       <h6 class="font_6">Nosso lema é: "A satisfação de nosso cliente é a nossa realização."</h6>
       <h6 class="font_6" style="line-height:1.3em; text-align:justify"><span>​</span></h6>
       <p class="font_8">Desenvolvemos sistemas que atendam as necessidade de sua empresa.</p>
       <p class="font_8">Os sistemas precisam se adequarem a empresa e não a empresa ao sistema para isso nos dispomos a atendê-lo.</p>
       <p class="font_8">Nossa satisfação é ver nossos clientes realizados. 
                          Faça uma experiência, teremos total prazer em apresentar uma solução ao 
                          teu negócio, mesmo sem compromisso você terá um tratamento "VIP".</p>
    </div>
    <div class="s2" id="FvGrdLnh" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$FvGrdLnh"></div>
    <div style="left: 20px; width: 883px; position: absolute; top: 12px;" class="s1" id="WRchTxt1l" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WRchTxt1l">
       <h2 class="font_2"><span style="line-height: 1.1em;"><span class="color_24">Sobre</span></span></h2>
    </div>
    <!--<div class="s2" id="FvGrdLnp" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$FvGrdLnp">
      <div id="FvGrdLnpline" class="s2line" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$FvGrdLnp.0"></div>
    </div>-->
    <div style="left: 830px; position: absolute; top: 83px; width: 133px; height: 135px;" data-exact-height="135" data-content-padding-horizontal="2" data-content-padding-vertical="2" title="" class="s10" id="WPht0" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WPht0">
       <img id="WPht0imgimage" alt="" src="img/84770f_35ad8b88adfc46a97fe3744e9bff1125.png" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WPht0.0.0.$image">
    </div>
    <div style="" class="s1" id="WRchTxtj" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WRchTxtj">
       <p class="font_7" style="line-height:1.3em; text-align:center"><span><span class="color_11">VENCEDOR</span></span></p>
       <p class="font_7" style="line-height:1.3em; text-align:center"><span><span class="color_11">​Seu sucesso é nosso sucesso</span></span></p>
    </div>
    <div class="s1" id="WRchTxt8" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$WRchTxt8">
      <h4 class="font_4"><span class="color_24">​</span>SERVIÇOS&nbsp;DE</h4>
      <h4 class="font_4">DESENVOLVIMENTO DE SISTEMAS</h4>
      <h5 class="font_5" style="line-height:1.3em"><span>LEIA NOSSO ALVO</span></h5>
    </div>
    <div class="s2" id="FvGrdLn9" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$FvGrdLn9">
                            <div id="FvGrdLn9line" class="s2line" data-reactid=".0.$SITE_ROOT.$desktop_siteRoot.$PAGES_CONTAINER.1.1.$SITE_PAGES.$c1enr_DESKTOP.1.$FvGrdLn9.0"></div>
    </div>
</div>